#model
model:
  model_name: res_unet
  dataset_name: DDR_HE
  img_size: 1024
  data_augment: True

  optim:
    type: "SGD"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

  lr_schedule:
#    mode: "min"
#    factor: 0.1
#    patience: 10
    min_lr: 0.0001
    t_max: 5000

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/HE/train"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/HE/test"
  num_workers: 4

  num_channels: 3
  num_classes: 2
  classes:
    - "bg"
    - "HE"

  slide_inference:
    slide_crop_size: 224
    slide_stride: 112

#client
client:
  gpu: "3"

  epoch: 1
  batch_size: 8
  eval_batch_size: 8

  log_interval_iter: 10

  ignore_loadavg: True

#server
server:
  host: "127.0.0.1"
  port: 9192
  gpu: "5"

  epoch: 5000
  num_clients: 2

  global_eval:
    # {type : metric to best}
    train:
      num: 500
      metric: "mIoU"
    test:
      num: 500
      metric: "mIoU"

  local_eval:
    # {type : global ep interval to eval}
    test: 250

  tolerate:
    test:
      num: 10
      metric: "mIoU"

  log_interval_iter: 10
  save_ckpt_epoch: 250
  per_client_max_loadavg: 0.8
