#model
model:
  model_name: unet
  dataset_name: ISIC
  img_size: 256
  data_augment: False

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/train"
    val: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/val"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/test"
  num_workers: 1

  num_channels: 3
  num_classes: 1
  classes:
    - "lesions"
  gpu: "4,5"

#client
client:
  epoch: 2
  batch_size: 4
  eval_batch_size: 4

  log_interval_iter: 10

  ignore_loadavg: True

#server
server:
  host: "127.0.0.1"
  port: 9191

  epoch: 300
  num_clients: 4

  global_eval:
    # {type : metric to best}
    train: "loss"
    val: "mIoU"
    test: "mIoU"

  local_eval:
    # {type : global ep interval to eval}
    val: 5
    test: 5

  tolerate:
    val:
      num: 5
      metric: "mIoU"

  log_interval_iter: 10
  save_ckpt_epoch: 40
  per_client_max_loadavg: 0.8
