#model
model:
  model_name: deeplabv3
  dataset_name: DDR
  img_size: 1024
  data_augment: True

  optim:
    type: "SGD"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

  lr_schedule:
#    mode: "min"
#    factor: 0.1
#    patience: 10
    min_lr: 0.0001
    t_max: 1000

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/train/crop_resize"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/test/crop_resize"
  num_workers: 1

  num_channels: 3
  num_classes: 5
  classes:
    - "bg"
    - "EX"
    - "HE"
    - "MA"
    - "SE"

  slide_inference:
    slide_crop_size: 224
    slide_stride: 112

#client
client:
  gpu: "4"

  epoch: 1
  batch_size: 8
  eval_batch_size: 1

  log_interval_iter: 10

  ignore_loadavg: True

#server
server:
  host: "127.0.0.1"
  port: 9191
  gpu: "5"

  epoch: 1000
  num_clients: 4

  global_eval:
    # {type : metric to best}
    train:
      num: 100
      metric: "mIoU"
    test:
      num: 100
      metric: "mIoU"

  local_eval:
    # {type : global ep interval to eval}
    test: 50

  tolerate:
    test:
      num: 10
      metric: "mIoU"

  log_interval_iter: 10
  save_ckpt_epoch: 100
  per_client_max_loadavg: 0.8
