#model
model:
  model_name: unet
  dataset_name: isic

#client
client:
  epoch: 5
  batch_size: 16
  eval_batch_size: 16
  num_channels: 3
  num_classes: 1
  log_interval: 10
  gpu: "4,5"

#server
server:
  epoch: 1000
  num_workers: 1
  num_clients: 5
  log_interval: 10