#model
model:
  model_name: unet
  dataset_name: isic
  dataset_txt:
    train: "..."
    val: "..."
    test: ".."

#client
client:
  epoch: 5
  batch_size: 16
  eval_batch_size: 16
  num_channels: 3
  num_classes: 1
  log_interval_iter: 10
  gpu: "4,5"

  ignore_loadavg: "false"

#server
server:
  epoch: 1000
  num_workers: 1
  num_clients: 5

  num_tolerate: 5
  type_tolerate: "val"

  log_interval_iter: 10

  eval:
    # eval_type : global epoch interval
    val: 5
    test: 5

  per_client_max_loadavg: 0.4
