#model
model:
  model_name: unet
  dataset_name: DDR
  img_size: 512
  data_augment: False

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/train"
    val: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/valid"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/test"
  num_workers: 1

  num_channels: 3
  num_classes: 4
  classes:
    - "EX"
    - "HE"
    - "MA"
    - "SE"
  gpu: "4,5"

#client
client:
  epoch: 2
  batch_size: 2
  eval_batch_size: 2

  log_interval_iter: 10

  ignore_loadavg: True

#server
server:
  host: "127.0.0.1"
  port: 9191

  epoch: 300
  num_clients: 2

  global_eval:
    - "train"
    - "val"
    - "test"
  local_eval:
    val: 5
    test: 5

  num_tolerate: 4
  type_tolerate: "val"

  log_interval_iter: 10
  per_client_max_loadavg: 0.8
