#model
model:
  model_name: res_unet
  dataset_name: ISIC
  img_size: 256
  data_augment: False

  optim:
    type: "SGD"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

  lr_schedule:
    #    mode: "min"
    #    factor: 0.1
    #    patience: 10
    min_lr: 0.0001
    t_max: 200

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/train"
    val: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/val"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/test"
  num_workers: 1

  num_channels: 3
  num_classes: 2
  classes:
    - "bg"
    - "lesions"

#client
client:
  gpu: "4"

  epoch: 2
  batch_size: 4
  eval_batch_size: 1

  log_interval_iter: 10

  ignore_loadavg: True

#server
server:
  host: "127.0.0.1"
  port: 9190
  gpu: "5"

  epoch: 100
  num_clients: 1

  global_eval:
    # {type : metric to best}
    train:
      num: 2
      metric: "mIoU"
    val:
      num: 2
      metric: "mIoU"
    test:
      num: 2
      metric: "mIoU"

  #  local_eval:
  #    # {type : global ep interval to eval}
  #    val: 5
  #    test: 5

  tolerate:
    val:
      num: 5
      metric: "mIoU"

  log_interval_iter: 10
  save_ckpt_epoch: 40
  per_client_max_loadavg: 0.8
