#model
model:
  model_name: res_unet
  dataset_name: DDR
  img_size: 512
  data_augment: True

  optim:
    type: "SGD"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

  lr_schedule:
    mode: "min"
    factor: 0.1
    patience: 10
    min_lr: 1e-5

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/train"
    val: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/val"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/DDR_lesion_segmentation/test"
  num_workers: 4

  num_channels: 3
  num_classes: 5
  classes:
    - "bg"
    - "EX"
    - "HE"
    - "MA"
    - "SE"

#client
client:
  gpu: "4"

  epoch: 2
  batch_size: 8
  eval_batch_size: 8

  log_interval_iter: 10

  ignore_loadavg: True

#server
server:
  host: "127.0.0.1"
  port: 9191
  gpu: "5"

  epoch: 200
  num_clients: 2

  global_eval:
    # {type : metric to best}
    train: "loss"
    val: "mIoU"
    test: "mIoU"

  local_eval:
    # {type : global ep interval to eval}
    val: 5
    test: 5

  tolerate:
    val:
      num: 5
      metric: "mIoU"

  log_interval_iter: 10
  save_ckpt_epoch: 40
  per_client_max_loadavg: 0.8
