#model
model:
  model_name: unet
  dataset_name: isic
  img_size: 256

  dataset_dir:
    train: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/train"
    val: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/val"
    test: "/home/maojingxin/workspace/Neko-ML/DRSegFL/datas/ISIC/test"
  num_workers: 1

  num_channels: 3
  num_classes: 1
  gpu: "4,5"

#client
client:
  epoch: 2
  batch_size: 16
  eval_batch_size: 16

  log_interval_iter: 10

  ignore_loadavg: "false"

#server
server:
  host: "127.0.0.1"
  port: 9191

  epoch: 100
  num_clients: 2

  num_tolerate: 5
  type_tolerate: "val"

  log_interval_iter: 10

  eval:
    # eval_type : global epoch interval
    val: 5
    test: 5

  per_client_max_loadavg: 0.4
